my_site/my_site/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import include, path
from drf_spectacular.views import (
    SpectacularAPIView,
    SpectacularRedocView,
    SpectacularSwaggerView,
)

from .sitemaps import sitemaps

urlpatterns = [
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path("admin/", admin.site.urls),
    path("req/", include("requestdataapp.urls")),
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    # Optional UI:
    path(
        'api/schema/swagger-ui/',
        SpectacularSwaggerView.as_view(url_name='schema'),
        name='swagger-ui',
    ),
    path('api/schema/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),
    path("api/", include("myapiapp.urls")),
    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
]

urlpatterns += i18n_patterns(
    path("accounts/", include("myauth.urls")),
    path("shop/", include("shop_app.urls")),
    path("blog/", include("blogapp.urls")),
)

if settings.DEBUG:
    urlpatterns.extend(static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))
    urlpatterns.extend(static(settings.STATIC_URL, document_root=settings.STATIC_ROOT))
    # urlpatterns = [*urlpatterns] + debug_toolbar_urls()
    # urlpatterns.append(path("__debug__/", include("debug_toolbar.urls")))

my_site/myauth/urls.py
from django.urls import path

from .views import (
    AboutMeUpdateView,
    AboutMeView,
    FooBarView,
    HelloView,
    MyLoginView,
    MyLogoutPage,
    ProfileDetailView,
    ProfilesListView,
    RegisterView,
    get_cookie_view,
    get_session_view,
    set_cookie_view,
    set_session_view,
)

app_name: str = "myauth"

urlpatterns = [
    # path("login/", login_view, name="login"),
    # path(
    #     "login/",
    #     LoginView.as_view(template_name="myauth/login.html", redirect_authenticated_user=True),
    #     name="login",
    # ),
    path("hello/", HelloView.as_view(), name="hello"),
    path("login/", MyLoginView.as_view(), name="login"),
    # path("logout/", logout_view, name="logout"),
    path("logout/", MyLogoutPage.as_view(), name="logout"),
    path("aboutme/<int:pk>/", AboutMeView.as_view(), name="about_me"),
    path("aboutme/<int:pk>/update/", AboutMeUpdateView.as_view(), name="about_me_update"),
    path("register/", RegisterView.as_view(), name="register"),
    path("profiles/", ProfilesListView.as_view(), name="profiles_list"),
    path("profiles/<int:pk>/", ProfileDetailView.as_view(), name="profiles_detail"),
    path(
        "cookie/set/",
        set_cookie_view,
        name="set_cookie",
    ),
    path(
        "cookie/get/",
        get_cookie_view,
        name="get_cookie",
    ),
    path(
        "session/set/",
        set_session_view,
        name="set_session",
    ),
    path(
        "session/get/",
        get_session_view,
        name="get_session",
    ),
    path("foobar/", FooBarView.as_view(), name="foo_bar"),
]

# if settings.DEBUG:
#     urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

my_site/shop_app/urls.py
"""
URL configuration for the shop application.

This module defines the URL patterns for the shop application, including
views for managing products, orders, and user groups. It uses Django's
path and include functions to route requests to the appropriate views.
"""

from django.urls import include, path
from rest_framework.routers import DefaultRouter

from .views import (
    GroupsListView,
    LatestProductsFeed,
    OrderCreateView,
    OrderDeleteView,
    OrdersDataExportView,
    OrdersDetailView,
    OrdersListView,
    OrderUpdateView,
    OrderViewSet,
    ProductCreateView,
    ProductDeleteView,
    ProductDetailsView,
    ProductsDataExportView,
    ProductsListView,
    ProductUpdateView,
    ProductViewSet,
    ShopIndexView,
    UserOrdersExportView,
    UserOrdersListView,
)

app_name: str = "shop_app"

routers = DefaultRouter()
routers.register(r"products", ProductViewSet, basename="product_set")
routers.register(r"orders", OrderViewSet, basename="order_set")

urlpatterns = [
    # path("", cache_page(60 * 3)(ShopIndexView.as_view()), name="index"),
    path("", ShopIndexView.as_view(), name="index"),
    path("groups/", GroupsListView.as_view(), name="group_list"),
    path("api/", include(routers.urls)),
    path("products/", ProductsListView.as_view(), name="product_list"),
    path("products/export/", ProductsDataExportView.as_view(), name="product_export"),
    path("products/create/", ProductCreateView.as_view(), name="product_create"),
    path("products/<int:pk>/", ProductDetailsView.as_view(), name="product_details"),
    path("products/<int:pk>/update/", ProductUpdateView.as_view(), name="product_update"),
    path("products/<int:pk>/archived/", ProductDeleteView.as_view(), name="product_archived"),
    path("products/latest/feed/", LatestProductsFeed(), name="product_feed"),
    path("orders/", OrdersListView.as_view(), name="order_list"),
    path("orders/export/", OrdersDataExportView.as_view(), name="order_export"),
    path("orders/create/", OrderCreateView.as_view(), name="order_create"),
    path("orders/<int:pk>/", OrdersDetailView.as_view(), name="order_details"),
    path("orders/<int:pk>/update/", OrderUpdateView.as_view(), name="order_update"),
    path("orders/<int:pk>/delete/", OrderDeleteView.as_view(), name="order_delete"),
    path("users/<int:user_id>/orders/", UserOrdersListView.as_view(), name="user_orders_list"),
    path(
        "users/<int:user_id>/orders/export/",
        UserOrdersExportView.as_view(),
        name="user_orders_export",
    ),
]

# if settings.DEBUG:
#     urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

my_site/shop_app/models.py
"""
Models for the shop application.

This module contains the data models for the shop application, including
products and orders. It defines the structure of the database tables and
the relationships between them.
"""

from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.utils.translation import pgettext_lazy


def product_preview_directory_path(instance: "Product", filename: str) -> str:
    """
    Generate the file path for product preview images.

    Args:
        instance (Product): The product instance for which the preview is being uploaded.
        filename (str): The original filename of the uploaded image.

    Returns:
        str: The file path for the product preview image.
    """
    return f"products/product_{instance.pk}/preview/{filename}"


class Product(models.Model):
    """
    The product model represents the product sold in the store.

    Orders here: :model:`shop_app.Order`
    """

    name = models.CharField(
        max_length=100, verbose_name=pgettext_lazy("product name", "name"), db_index=True
    )
    description = models.TextField(
        null=False, blank=True, verbose_name=_("description"), db_index=True
    )
    price = models.DecimalField(default=0, max_digits=10, decimal_places=2, verbose_name=_("price"))
    discount = models.PositiveSmallIntegerField(default=0, verbose_name=_("discount"))
    created_at = models.DateTimeField(auto_now_add=True, verbose_name=_("created at"))
    archived = models.BooleanField(default=False, verbose_name=_("archived"))
    created_by = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="products",
        null=True,
        verbose_name=_("created by"),
    )
    preview = models.ImageField(
        null=True, blank=True, upload_to=product_preview_directory_path, verbose_name=_("preview")
    )

    class Meta:
        """
        Meta options for the Product model.

        Attributes:
            ordering (list): Default ordering for the Product model.
            verbose_name (str): Singular name for the Product model.
            verbose_name_plural (str): Plural name for the Product model.
        """

        ordering = ["name", "price"]
        verbose_name = _("product")  # перевод будет отражен в админ-панели
        verbose_name_plural = _("products")

    def __str__(self) -> str:
        """
        Return a string representation of the product.

        Returns:
            str: A string representation of the product including its name and price.
        """
        # return f"{_('Product')} '{self.name}', {_('price')} {self.price} у.е."
        return _("Product '%(name)s', price %(price)d у.е.") % {
            "name": self.name,
            "price": self.price,
        }

    def get_absolute_url(self) -> str:
        """Returns the absolute URL for the model Product"""
        return reverse("shop_app:product_details", kwargs={"pk": self.pk})


def product_images_directory_path(instance: "ProductImage", filename: str) -> str:
    """
    Generate the file path for product images.

    Args:
        instance (ProductImage): The product image instance for which the image is being uploaded.
        filename (str): The original filename of the uploaded image.

    Returns:
        str: The file path for the product image.
    """
    return "products/product_{pk}/images/{filename}".format(
        pk=instance.product.pk, filename=filename
    )


class ProductImage(models.Model):
    """
    The product image model represents images associated with a product.

    Attributes:
        product (Product): The product associated with this image.
        image (ImageField): The image file for the product.
        description (str): A description of the image.
    """

    product = models.ForeignKey(
        Product,
        on_delete=models.CASCADE,
        related_name="images",
        verbose_name=pgettext_lazy("product id", "product"),
    )
    image = models.ImageField(upload_to=product_images_directory_path, verbose_name=_("image"))
    description = models.CharField(
        max_length=200, null=False, blank=True, verbose_name=_("description")
    )

    class Meta:
        """
        Meta options for the ProductImage model.

        Attributes:
            verbose_name (str): Singular name for the ProductImage model.
            verbose_name_plural (str): Plural name for the ProductImage model.
        """

        verbose_name = _("product image")
        verbose_name_plural = _("product images")

    def __str__(self) -> str:
        """
        Return a string representation of the product image.

        Returns:
            str: A string representation of the product image, indicating
            the associated product's name.
        """
        return _("Product image %s") % (self.product.name,)


class Order(models.Model):
    """
     The order model represents a customer's order containing products and delivery information.

     Products here: :model:`shop_app.Product`

    Attributes:
        user (User ): The user who placed the order.
        products (ManyToManyField): The products included in the order.
        promocode (str): An optional promocode applied to the order.
        delivery_address (str): The address where the order will be delivered.
        created_at (datetime): The timestamp when the order was created.
        receipt (FileField): An optional receipt file associated with the order.
    """

    user = models.ForeignKey(
        User,
        on_delete=models.PROTECT,
        related_name="orders",
        verbose_name=pgettext_lazy("user id", "user"),
    )
    products = models.ManyToManyField(Product, related_name="orders", verbose_name=_("products"))
    promocode = models.CharField(max_length=20, null=False, blank=True, verbose_name=_("promocode"))
    delivery_address = models.TextField(verbose_name=_("delivery address"))
    created_at = models.DateTimeField(auto_now_add=True, verbose_name=_("created at"))
    receipt = models.FileField(
        verbose_name=_("Receipt"),
        blank=True,
        null=True,
        upload_to="orders/receipts/",
    )

    class Meta:
        """
        Meta options for the Order model.

        Attributes:
            verbose_name (str): Singular name for the Order model.
            verbose_name_plural (str): Plural name for the Order model.
        """

        verbose_name = _("order")
        verbose_name_plural = _("orders")

    def __str__(self) -> str:
        """
        Return a string representation of the order.

        Returns:
            str: A string representation of the order, including its order number.
        """
        return _("Order № %s") % (self.pk)

    def get_absolute_url(self) -> str:
        """Returns the absolute URL for the model Order"""
        return reverse("shop_app:order_details", kwargs={"pk": self.pk})

my_site/shop_app/forms.py
from django import forms
from django.contrib.auth.models import Group
from django.utils.translation import gettext_lazy as _, pgettext_lazy

from .models import Order, Product

# from django.core import validators


# class ProductForm(forms.Form):
#     name = forms.CharField(max_length=100)
#     price = forms.DecimalField(min_value=1, max_value=1000000, decimal_places=2)
#     description = forms.CharField(
#         label="Product description",
#         widget=forms.Textarea(attrs={"cols": 5, "rows": "30"}),
#         validators=[
#             validators.RegexValidator(regex="great", message="Field must contain word 'great'")
#         ],
#     )


# If you want to upload multiple files using one form field, create a subclass of the field’s widget
# and set its allow_multiple_selected class attribute to True.
class MultipleFileInput(forms.ClearableFileInput):
    allow_multiple_selected = True


class MultipleFileField(forms.FileField):
    def __init__(self, *args, **kwargs):
        kwargs.setdefault("widget", MultipleFileInput())
        super().__init__(*args, **kwargs)

    def clean(self, data, initial=None):
        single_file_clean = super().clean
        if isinstance(data, (list, tuple)):
            result = [single_file_clean(d, initial) for d in data]
        else:
            result = [single_file_clean(data, initial)]
        return result


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ["name", "price", "description", "discount", "preview"]
        widgets = {
            "description": forms.Textarea(attrs={"cols": 30, "rows": 5}),
        }
        labels = {
            "name": pgettext_lazy("product name", "Name"),
            "price": _("Price"),
            "description": _("Product description"),
            "discount": _("Discount"),
            "preview": _("Preview"),
        }

    # устарело ClearableFileInput и multiple
    # images = forms.ImageField(widget=forms.ClearableFileInput(attrs={"multiple": True}))
    images = MultipleFileField(required=False, label=_("Images"))


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = [
            "user",
            "products",
            "promocode",
            "delivery_address",
            "receipt",
        ]
        widgets = {
            "delivery_address": forms.Textarea(attrs={"cols": 30, "rows": 5}),
        }
        labels = {
            "user": _("Customer"),
            "products": _("List of products"),
            "promocode": _("Promocode"),
            "delivery_address": _("Delivery address"),
        }
        error_messages = {
            "promocode": {
                "max_length": ("The promo code is too long."),
            }
        }


class GroupForm(forms.ModelForm):

    class Meta:
        model = Group
        fields = ["name"]
        labels = {"name": pgettext_lazy("group name", "Name")}


class FileImportForm(forms.Form):
    uploaded_file = forms.FileField(label=_("file"))

my_site/shop_app/templates/shop_app/base.html
<!DOCTYPE html>
{% load static i18n%}
<html lang="{% get_current_language as language_code %}">
  <head>
    <meta charset="UTF-8" />
    <title>
      {% block title %}
        {% translate 'Base title' %}
      {% endblock %}
    </title>
    <link rel="stylesheet" type="text/css" href="{% static 'shop_app/css/style.css' %}" />
    <script src="{% static 'shop_app/js/script.js' %}" defer></script>
    {% comment %}подключаем шрифт Roboto с сервиса Google Fonts{% endcomment %}
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,400;0,700;1,400;1,700&display=swap" />
    {% comment %}подключаем bootstrap для дизайна form{% endcomment %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous" />
  </head>
  <body>
    <header>
      <div class="link-container">
        <div>
          <nav>
            {% for value in urls_page_path %}
              {% if request.path != value.2 %}
                <a class="link-shop-app" href="{% url value.0 %}">{{ value.1 }}</a>
              {% endif %}
            {% endfor %}
          </nav>
        </div>
        <div class="user-auth">
          {% if user.is_authenticated %}
            <span>
              {% translate 'User:' %}
              <a class="link-shop-app" href="{% url 'myauth:about_me' pk=user.pk %}">{{ user.username|capfirst }}</a>
            </span>
            {% if user.email %}
              <span>{% translate 'Email:' %} {{ user.email }}</span>
            {% endif %}
            <button id="logoutButton">{% translate 'Logout' %}</button>
          {% else %}
            <button id="loginButton">{% translate 'Login' %}</button>
          {% endif %}
        </div>
      </div>
    </header>
    {% block body %}
      Base body
    {% endblock %}
    <div>
      {% now 'DATETIME_FORMAT' %}
    </div>
    <div>
      {% translate 'Today is' %} {% now 'l' %}
    </div>
  </body>
</html>

my_site/shop_app/templates/shop_app/create-product.html
{% extends 'shop_app/base.html' %}

{% block title %}
  Create product
{% endblock %}

{% block body %}
  <h1>Create a new product</h1>
  <div>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Create</button>
    </form>
  </div>
  <nav>
    <a class="link-shop-app" nav href="{% url 'shop_app:product_list' %}">Back to products list</a>
  </nav>
{% endblock %}

my_site/shop_app/templates/shop_app/order_create.html
{% extends 'shop_app/base.html' %}
{% load i18n %}

{% block title %}
  {% trans 'Create order' %}
{% endblock %}

{% block body %}
  <h1>{% trans 'Create a new order' %}</h1>

  <div>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">{% trans 'Create' %}</button>
    </form>
  </div>
  <br />

  <nav>
    <li>
      <a class="link-shop-app" href="{% url 'shop_app:order_list' %}">{% trans 'Back to order list' %}</a>
    </li>
  </nav>
  <br />
{% endblock %}

my_site/shop_app/templates/shop_app/order_delete.html
{% extends 'shop_app/base.html' %}
{% load i18n %}

{% block title %}
  {% trans 'Confirm archived' %} {{ object.name }}
{% endblock %}

{% block body %}
  <h1>{% trans 'Are you sure you want to delete order' %}&nbsp;#{{ object.pk }}?</h1>
  <br />
  <div>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button class="button-delete" type="submit">{% trans 'Delete' %}</button>
    </form>
  </div>
  <br />
  <nav>
    <a class="link-shop-app" href="{% url 'shop_app:order_details' pk=object.pk %}">{% trans 'Back to order' %}&nbsp;#{{ object.pk }}</a>
  </nav>
  <br />
{% endblock %}

my_site/shop_app/templates/shop_app/order_detail.html
{% extends 'shop_app/base.html' %}
{% load i18n %}

{% block title %}
  {% blocktrans with pk=object.pk %}Order #{{ pk }} details{% endblocktrans %}
{% endblock %}

{% block body %}
  <h1>{% blocktrans with pk=object.pk %}Order #{{ pk }}{% endblocktrans %}</h1>
  <div>
    <p>
      {% trans 'Order by' %} {% firstof object.user.first_name object.user.username %}
    </p>
    <p>
      {% trans 'Promocode' %}: <code>{{ object.promocode }}</code>
    </p>
    <p>
      {% trans 'Delivery address' %}: {{ object.delivery_address }}
    </p>
    <div>
      {% trans 'Products in orders' %}:<ol>
        {% for product in object.products.all %}
          <li>
            {{ product.name }} {% trans 'for' %}&nbsp;${{ product.price }}
          </li>
        {% endfor %}
      </ol>
    </div>
  </div>
  <nav>
    <ul>
      <li>
        <a class="link-shop-app" href="{% url 'shop_app:order_update' pk=object.pk %}">{% trans 'Update order' %}</a>
      </li>
      <li>
        <a class="link-shop-app" href="{% url 'shop_app:order_delete' pk=object.pk %}">{% trans 'Delete order' %}</a>
      </li>
      <li>
        <a class="link-shop-app" href="{% url 'shop_app:order_list' %}">{% trans 'Back to orders' %}</a>
      </li>
    </ul>
  </nav>
  <br />
{% endblock %}

my_site/shop_app/templates/shop_app/order_list.html
{% extends 'shop_app/base.html' %}
{% load i18n %}

{% block title %}
  {% trans 'Orders list' %}
{% endblock %}

{% block body %}
  <h1>{% trans 'Orders' %}:</h1>

  {% if object_list %}
    <div>
      {% for order in object_list %}
        <div>
          <p>
            <a class="link-shop-app" href="{% url 'shop_app:order_details' pk=order.pk %}">{% trans 'Details' %}&nbsp;#{{ order.pk }}</a>
          </p>
          <p>
            {% trans 'Order by' %} {% firstof order.user.first_name order.user.username %}
            <a class="link-shop-app" href="{% url 'shop_app:user_orders_list' user_id=order.user.pk %}">{% trans ' - view all orders of the user' %}</a>
          </p>
          <p>
            {% trans 'Promocode' %}: <code>{{ order.promocode }}</code>
          </p>
          <p>
            {% trans 'Delivery address' %}: {{ order.delivery_address }}
          </p>
          <div>
            {% trans 'Products in orders' %}:<ol>
              {% for product in order.products.all %}
                <li>
                  {{ product.name }} {% trans 'for' %}&nbsp;${{ product.price }}
                </li>
              {% endfor %}
            </ol>
          </div>
        </div>
      {% endfor %}
    </div>
  {% else %}
    <h3>{% trans 'No orders yet' %}</h3>
  {% endif %}

  <nav>
    <li>
      <a class="link-shop-app" href="{% url 'shop_app:order_create' %}">{% trans 'Create a new order' %}</a>
    </li>
  </nav>
  <br />
{% endblock %}

my_site/shop_app/templates/shop_app/order_update.html
{% extends 'shop_app/base.html' %}
{% load i18n %}

{% block title %}
  {% trans 'Update order' %}
{% endblock %}

{% block body %}
  <h1>{% trans 'Update order' %}</h1>
  <div>
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">{% trans 'Update' %}</button>
    </form>
  </div>
  <br />
  <nav>
    <a class="link-shop-app" href="{% url 'shop_app:order_details' pk=object.pk %}">{% trans 'Back to order' %}&nbsp;#{{ object.pk }}</a>
  </nav>
  <br />
{% endblock %}

my_site/shop_app/templates/shop_app/product_archived.html
{% extends 'shop_app/base.html' %}
{% load i18n %}
{% block title %}
  {% trans 'Confirm archived' %} {{ object.name }}
{% endblock %}
{% block body %}
  <h1>{% trans 'Are you sure you want to archived' %} {{ object.name }}?</h1>
  <br />
  <div>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button class="button-delete" type="submit">{% trans 'Archived' %}</button>
    </form>
  </div>
  <br />
  <nav>
    <a class="link-shop-app" href="{% url 'shop_app:product_details' pk=object.pk %}">{% trans 'Back to product' %} {{ object.name }}</a>
  </nav>
  <br />
{% endblock %}

my_site/shop_app/templates/shop_app/products-details.html
{% extends 'shop_app/base.html' %}
{% load i18n %}
{% block title %}
  {% translate 'Product' %}&nbsp;#{{ product.pk }}
{% endblock %}
{% block body %}
  <h1>{% translate 'Product' %} <strong>{{ product.name }}</strong></h1>

  <div>
    {% blocktrans with description=product.description price=product.price discount=product.discount archived=product.archived %}
    <div>
      Description: <em>{{ description }}</em>
    </div>
    <div>Price: {{ price }}$</div>
    <div>Discount: {{ discount }}%</div>
    <div>Archived: {{ archived }}</div>
    {% endblocktrans %}
    <div>
      {% if product.preview %}
        <img src="{{ product.preview.url }}" alt="{{ product.preview.name }}" />
      {% endif %}
      <br />
      <h3>{% translate 'Images:' %}</h3>
      <div>
        {% blocktrans count images_count=product.images.all|length %}There is only one image.{% plural %}There are {{ images_count }} images.{% endblocktrans %}
      </div>
      <div>
        {% for img in product.images.all %}
          <img class="img-details" src="{{ img.image.url }}" alt="{{ img.image.name }}" />
          <div>{{ img.description }}</div>
        {% empty %}
          <p>
            {% translate 'No images available.' %}
          </p>
        {% endfor %}
      </div>
    </div>
  </div>
  <br />
  <nav>
    <ul>
      {% if user.is_superuser or user == product.created_by and perms.shop_app.change_product %}
        <li>
          <a class="link-shop-app" href="{% url 'shop_app:product_update' pk=product.pk %}">{% translate 'Update product' %}</a>
        </li>
        <li>
          <a class="link-shop-app" href="{% url 'shop_app:product_archived' pk=product.pk %}">{% translate 'Archived product' %}</a>
        </li>
      {% endif %}
      <li>
        <a class="link-shop-app" href="{% url 'shop_app:product_list' %}">{% translate 'Back to products list' %}</a>
      </li>
    </ul>
  </nav>
  <br />
{% endblock %}

my_site/shop_app/templates/shop_app/products-list.html
{% extends 'shop_app/base.html' %}
{% load i18n %}

{% block title %}
  {% translate 'Products list' %}
{% endblock %}

{% block body %}
  <h1>{% translate 'Products' %}</h1>
  {% if products %}
    <div>
      {% blocktrans count products_count=products|length %}There is only one product.{% plural %}There are {{ products_count }} products.{% endblocktrans %}
    </div>
    <div>
      <table class="price-list">
        <thead>
          <tr>
            <th>№</th>
            <th>
              {% translate 'Name' context 'product name' %}
            </th>
            <th>
              {% translate 'Price' %}
            </th>
            <th>
              {% translate 'Discount' %}
            </th>
            <th>
              {% translate 'Image' %}
            </th>
          </tr>
        </thead>
        <tbody>
          {% for product in products %}
            <tr>
              <td>{{ forloop.counter }}</td>
              <td>
                <a class="link-shop-app" href="{% url 'shop_app:product_details' pk=product.pk %}">{{ product.name }}</a>
              </td>
              <td>{{ product.price }}</td>
              <td>
                {% translate 'no discount' as no_discount %}
                {% firstof product.discount no_discount %}
              </td>
              <td>
                {% if product.preview %}
                  <img class="img-preview" src="{{ product.preview.url }}" alt="{{ product.preview.name }}" />
                {% endif %}
              </td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
    {% if perms.shop_app.add_product %}
      <br />
      <nav>
        <a class="link-shop-app" href="{% url 'shop_app:product_create' %}">{% translate 'Create a new product' %}</a>
      </nav>
    {% endif %}
    <br />
  {% else %}
    {% if perms.shop_app.add_product %}
      {% url 'shop_app:product_create' as create_product_url %}
      {% blocktrans %}<h3>No products yet</h3>
      <br />
      <nav>
        <a class="link-shop-app" href="{{ create_product_url }}">Create a new one</a>
      </nav>
      {% endblocktrans %}
    {% endif %}
    <br />
  {% endif %}
{% endblock %}